#!/bin/bash

# Help instructions
function usage()
{
    printf "\nCommand script for Sen2Cor atmospheric correction package [dockerized].\n"
    printf "Example usage: ./s2c [-h|--help] [-r|--resolution {10,20,60}] [-O|--output-folder] S2B_MSIL1C_SCENE-ID.SAFE\n\n"
    printf "Parameters:\n"
    printf "  -h --help\t\tHelp \n"
    printf "  -r --resolution\tTarget resolution, can be 10, 20 or 60. OPTIONAL: default all resolutions will be processed\n"
    printf "  -O --output-folder\tSpecify output folder. OPTIONAL: default will be input data folder\n\n"
}

function check_path()  # Will check if output path is absolute or relative
{
  initial="$(echo $1 | head -c 1)"
  if [ "$initial" = "/" ]; then
    is_absolute=true
  else
    is_absolute=false
  fi
}

function check_dir_exists()  # Will check and eventually create output folder
{
  if [ ! -d "$1" ]; then
    mkdir -p $1
  fi
}

function check_resolution()  # Ensure input resolution value is acceptable
{
  if [ ! -z "$1" ]; then # RESOLUTION is not empty value
    if [ "$1" -ne 10 -a "$1" -ne 20 -a "$1" -ne 60 ]; then
      printf "Wrong resolution value. Target resolution can be 10, 20 or 60m (default all). Exiting...\n"
      exit
    fi
  fi
}

# Parameters parser
PARAMS=""
while (( "$#" )); do
  case "$1" in
        -h|--help)
            usage
            exit
            ;;
        -r|--resolution)
            RESOLUTION="$2"
            PARAMS="--resolution $2 "
            shift 2
            ;;
        -O|--output-folder)
            DATA_OUTPUT=$2
            shift 2
            ;;
        --)
            shift
            break
            ;;
         *) # preserve positional arguments
            FILENAME=$1
            BASENAME=$(basename "$1")
            PARAMS="$PARAMS data/$BASENAME"
            shift
            ;;
    esac
done

# In case no parameters are given, exit with Help info
if [ -z "$PARAMS" ]; then
  usage
  exit
fi

# In case no filename was given exit and display help and message.
if [ -z "$FILENAME" ]; then
  printf "\nPlease indicate the SAFE container to convert. See Help usage example...\n"
  usage
  exit
fi
# End parser

# Setting up input and output paths
# Get folder of input data
check_path $FILENAME
FILENAME_DIR=$(dirname "${FILENAME}")
echo $FILENAME_DIR
if [ "$is_absolute" = "false" ]; then
  if [ "$FILENAME_DIR" = "." ]; then
    DATA_INPUT=$PWD
  else
    DATA_INPUT=$PWD$FILENAME_DIR
  fi
else
  DATA_INPUT=$FILENAME_DIR
fi

echo data_out: $DATA_OUTPUT
# Check if DATA_OUTPUT was set, in case
if [ -z "$DATA_OUTPUT" ]; then
  DATA_OUTPUT=$DATA_INPUT
fi

check_path $DATA_OUTPUT
if [ "$DATA_INPUT" = "$DATA_OUTPUT" ]; then
    echo input and output folder: $DATA_INPUT
else
    if [ "$is_absolute" = "false" ]; then
      DATA_OUTPUT=$PWD/$DATA_OUTPUT
      echo input folder: $DATA_INPUT
      echo output folder: $DATA_OUTPUT
    else
      echo input folder: $DATA_INPUT
      echo output folder: $DATA_OUTPUT
    fi
fi

check_dir_exists $DATA_OUTPUT
check_resolution $RESOLUTION
# echo params: $PARAMS

# docker run --rm -v $DATA_INPUT:/sen2cor/data s2c-test4 $PARAMS

if [ "$DATA_INPUT" != "$DATA_OUTPUT" ]; then
    echo mv data to output # todo
fi
